version: '2'
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.7.0
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "c2_track:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      JMX_PORT: 1099
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-manager:
    container_name: kafka-manager
    image: hlebalbau/kafka-manager:stable
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181